# Generated by Django 5.2.4 on 2025-07-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='new_field',
            field=models.BooleanField(default=False),
        ),
    ]
